### ISSUE TITLE
Suggestion: Drag and drop ISO

### ISSUE THREAD

**Issue by spsf64** [daltomi/ArchIsoMyDrive#1]
@daltomi Is it possible to implement this feature "drag and drop" the ISO/IMG file into the "Open an ISO file:" box?
The problem is a save my ISOs to an external HDD and it is always a pain to find the mount point using the browser from "Open" button... (like: /run/media/username/device/path/to/isos).
I use cinnamon DE.

Also, maybe you could change the text  "Open an ISO file:" to "Open an ISO or IMG file:"

Thanks again for this great project!

**Comment by daltomi** [comment]
Hi @spsf64 

Thanks for the suggestions, I will implement them soon.

**Comment by spsf64** [comment]
Ver 4.4 working 100%!! Amazing!
Thanks
Maybe just a cosmetic addition to the text:
"Open an ISO / IMG file or Drag and Drop into the Box below"
What do you think??

**Comment by daltomi** [comment]
Yes, you're right. Thank you.

**Comment by spsf64** [comment]
4.6 is perfect!
Thank you!
Closing
